chore: remove unecessary code
Changes:
  - Define and use integration tests decorator.
  - Remove logic to infer the webserver under test base image.
  - Set the nginx flavor for openresty.
  - Fix module version printing.
  - Reuse `test` job for openresty.

diff --git a/test/bin/run b/test/bin/run
--- a/test/bin/run
+++ b/test/bin/run
@@ -1,4 +1,10 @@
 #!/bin/sh
+set -e 
+
+if [ -z "${BASE_IMAGE}" ]; then
+  printf "Missing \"BASE_IMAGE\" environment variable.\n" >&2 
+  exit 1
+fi
 
 if [ -z "${ARCH}" ]; then
     ARCH="$(arch)"
@@ -7,19 +13,10 @@ fi
 
 cd "$(dirname "$0")/../"
 
-set -e
-
-if [ -z "${BASE_IMAGE}" ]; then
-    if [ -z "${RESTY_VERSION}" ]; then
-        export BASE_IMAGE="nginx:${NGINX_VERSION}-alpine"
-    else
-        export BASE_IMAGE="openresty/openresty:${RESTY_VERSION}-alpine"
-    fi
-fi
-
 printf "      arch : %s\n" "${ARCH}"
 printf "base image : %s\n" "${BASE_IMAGE}"
 printf " test args : %s\n" "$@"
 
 docker compose build --parallel --progress=plain
 python3 -m unittest "$@"
+
