code review

diff --git a/example/bin/run b/example/bin/run
--- a/example/bin/run
+++ b/example/bin/run
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/bin/sh
 set -e
 
 cd "$(dirname "$0")"/..
@@ -6,13 +6,13 @@ cd "$(dirname "$0")"/..
 BASE_IMAGE="${BASE_IMAGE:-nginx:1.23.1-alpine}"
 export BASE_IMAGE
 
-# Failfast in case the base image is not supported
-# For now, we only supported nginx and nginx-alpine images.
+# Fail fast in case the base image is not supported.
+# For now, we only support nginx, nginx-alpine, and amazonlinux images.
 case "$BASE_IMAGE" in
     amazonlinux:*) ;;
     nginx:*) ;;
     *)
-      >&2 echo 'Unsupported platform.'
+      >&2 echo 'BASE_IMAGE value "%s" is invalid. See nginx-version-info.example for more information.' "$BASE_IMAGE"
       exit 1
       ;;
 esac
